name: ping-supabase

on:
  schedule:
    # 09:00 Israel time year-round (cover DST with two UTC times)
    - cron: '0 6 * * 1,4'   # 06:00 UTC = 09:00 Israel in summer (UTC+3)
    - cron: '0 7 * * 1,4'   # 07:00 UTC = 09:00 Israel in winter (UTC+2)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: "Ping Supabase (read-only via Storage REST)"
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}
        shell: bash
        run: |
          set -euo pipefail
          # jitter so many repos don't hit at the same second
          sleep $((RANDOM % 90))
          # Read-only call that still wakes the project
          curl -sS -f \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            "${SUPABASE_URL}/storage/v1/bucket" \
            > /dev/null
          echo "Ping OK ✅"
