name: Ping Supabase to Prevent Pausing

on:
  schedule:
    # 09:00 Israel time all year (runs twice to cover DST shifts)
    - cron: '0 6 * * 1,4'   # 06:00 UTC = 09:00 Israel in summer (UTC+3)
    - cron: '0 7 * * 1,4'   # 07:00 UTC = 09:00 Israel in winter (UTC+2)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase client
        run: npm i @supabase/supabase-js --silent

      - name: Ping Supabase (read-only: list buckets)
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}
        run: |
          set -e
          sleep $((RANDOM % 90))  # jitter
          cat > ping.js <<'EOF'
          const { createClient } = require('@supabase/supabase-js');
          const url = process.env.SUPABASE_URL;
          const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

          if (!url || !key) {
            console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.');
            process.exit(1);
          }

          const supabase = createClient(url, key, { auth: { persistSession: false } });

          (async () => {
            try {
              const { data, error } = await supabase.storage.listBuckets();
              if (error) throw error;
              console.log('Ping OK. Buckets count:', Array.isArray(data) ? data.length : 'n/a');
            } catch (e) {
              console.error('Ping failed:', e?.message || e);
              process.exit(1);
            }
          })();
          EOF

          node ping.js
