name: Ping Supabase to Prevent Pausing

on:
  schedule:
    # 09:00 Israel time year-round (cover DST with two UTC times)
    - cron: '0 6 * * 1,4'   # 06:00 UTC = 09:00 IDT (summer)
    - cron: '0 7 * * 1,4'   # 07:00 UTC = 09:00 IST (winter)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase (read-only via Storage REST)
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}
        run: |
          set -e
          # Small jitter so many repos don't hit at exactly the same second
          sleep $((RANDOM % 90))
          # List storage buckets (read-only). Any 2xx means the project is awake.
          curl -sS -f \
            -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            "$SUPABASE_URL/storage/v1/bucket" > /dev/null
          echo "Ping OK ✅"
